/*
 * TroopTrack API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// MailingListEntity : MailingListEntity model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailingListEntity {
    /// Name used to identify the mailing list
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID of the mailing list record
    #[serde(rename = "mailing_list_id", skip_serializing_if = "Option::is_none")]
    pub mailing_list_id: Option<i32>,
    /// Email address of the mailing list
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl MailingListEntity {
    /// MailingListEntity model
    pub fn new() -> MailingListEntity {
        MailingListEntity {
            name: None,
            mailing_list_id: None,
            email: None,
        }
    }
}

