/*
 * API title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TroopPhotoEntity {
    /// ID of the Troop Photo record
    #[serde(rename = "troop_photo_id", skip_serializing_if = "Option::is_none")]
    pub troop_photo_id: Option<i32>,
    /// URL of the photo
    #[serde(rename = "photo", skip_serializing_if = "Option::is_none")]
    pub photo: Option<String>,
    /// URL of the thumbnail image
    #[serde(rename = "thumb", skip_serializing_if = "Option::is_none")]
    pub thumb: Option<String>,
}

impl TroopPhotoEntity {
    pub fn new() -> TroopPhotoEntity {
        TroopPhotoEntity {
            troop_photo_id: None,
            photo: None,
            thumb: None,
        }
    }
}

