/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EventTypeEntity model
 */
@Schema(description = "EventTypeEntity model")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class EventTypeEntity {
  @SerializedName("event_type_id")
  private Integer eventTypeId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("color")
  private String color = null;

  public EventTypeEntity eventTypeId(Integer eventTypeId) {
    this.eventTypeId = eventTypeId;
    return this;
  }

   /**
   * ID of the event type record
   * @return eventTypeId
  **/
  @Schema(description = "ID of the event type record")
  public Integer getEventTypeId() {
    return eventTypeId;
  }

  public void setEventTypeId(Integer eventTypeId) {
    this.eventTypeId = eventTypeId;
  }

  public EventTypeEntity name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the event type (Campout, Meeting, etc)
   * @return name
  **/
  @Schema(description = "Name of the event type (Campout, Meeting, etc)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EventTypeEntity color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Color used to display events of this type on the TroopTrack calendar
   * @return color
  **/
  @Schema(description = "Color used to display events of this type on the TroopTrack calendar")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventTypeEntity eventTypeEntity = (EventTypeEntity) o;
    return Objects.equals(this.eventTypeId, eventTypeEntity.eventTypeId) &&
        Objects.equals(this.name, eventTypeEntity.name) &&
        Objects.equals(this.color, eventTypeEntity.color);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventTypeId, name, color);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventTypeEntity {\n");
    
    sb.append("    eventTypeId: ").append(toIndentedString(eventTypeId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
