/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MailingListsIdBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class MailingListsIdBody {
  @SerializedName("message[subject]")
  private String messageSubject = null;

  @SerializedName("message[body]")
  private String messageBody = null;

  public MailingListsIdBody messageSubject(String messageSubject) {
    this.messageSubject = messageSubject;
    return this;
  }

   /**
   * Get messageSubject
   * @return messageSubject
  **/
  @Schema(required = true, description = "")
  public String getMessageSubject() {
    return messageSubject;
  }

  public void setMessageSubject(String messageSubject) {
    this.messageSubject = messageSubject;
  }

  public MailingListsIdBody messageBody(String messageBody) {
    this.messageBody = messageBody;
    return this;
  }

   /**
   * Get messageBody
   * @return messageBody
  **/
  @Schema(required = true, description = "")
  public String getMessageBody() {
    return messageBody;
  }

  public void setMessageBody(String messageBody) {
    this.messageBody = messageBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailingListsIdBody mailingListsIdBody = (MailingListsIdBody) o;
    return Objects.equals(this.messageSubject, mailingListsIdBody.messageSubject) &&
        Objects.equals(this.messageBody, mailingListsIdBody.messageBody);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageSubject, messageBody);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailingListsIdBody {\n");
    
    sb.append("    messageSubject: ").append(toIndentedString(messageSubject)).append("\n");
    sb.append("    messageBody: ").append(toIndentedString(messageBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
