/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MailingListEntity model
 */
@Schema(description = "MailingListEntity model")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class MailingListEntity {
  @SerializedName("name")
  private String name = null;

  @SerializedName("mailing_list_id")
  private Integer mailingListId = null;

  @SerializedName("email")
  private String email = null;

  public MailingListEntity name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name used to identify the mailing list
   * @return name
  **/
  @Schema(description = "Name used to identify the mailing list")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MailingListEntity mailingListId(Integer mailingListId) {
    this.mailingListId = mailingListId;
    return this;
  }

   /**
   * ID of the mailing list record
   * @return mailingListId
  **/
  @Schema(description = "ID of the mailing list record")
  public Integer getMailingListId() {
    return mailingListId;
  }

  public void setMailingListId(Integer mailingListId) {
    this.mailingListId = mailingListId;
  }

  public MailingListEntity email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email address of the mailing list
   * @return email
  **/
  @Schema(description = "Email address of the mailing list")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailingListEntity mailingListEntity = (MailingListEntity) o;
    return Objects.equals(this.name, mailingListEntity.name) &&
        Objects.equals(this.mailingListId, mailingListEntity.mailingListId) &&
        Objects.equals(this.email, mailingListEntity.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, mailingListId, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailingListEntity {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mailingListId: ").append(toIndentedString(mailingListId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
