/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PhotoAlbumsIdBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class PhotoAlbumsIdBody {
  @SerializedName("photo_file_extension")
  private String photoFileExtension = null;

  @SerializedName("photo_file_content")
  private String photoFileContent = null;

  @SerializedName("album_name")
  private String albumName = null;

  public PhotoAlbumsIdBody photoFileExtension(String photoFileExtension) {
    this.photoFileExtension = photoFileExtension;
    return this;
  }

   /**
   * Get photoFileExtension
   * @return photoFileExtension
  **/
  @Schema(required = true, description = "")
  public String getPhotoFileExtension() {
    return photoFileExtension;
  }

  public void setPhotoFileExtension(String photoFileExtension) {
    this.photoFileExtension = photoFileExtension;
  }

  public PhotoAlbumsIdBody photoFileContent(String photoFileContent) {
    this.photoFileContent = photoFileContent;
    return this;
  }

   /**
   * Get photoFileContent
   * @return photoFileContent
  **/
  @Schema(required = true, description = "")
  public String getPhotoFileContent() {
    return photoFileContent;
  }

  public void setPhotoFileContent(String photoFileContent) {
    this.photoFileContent = photoFileContent;
  }

  public PhotoAlbumsIdBody albumName(String albumName) {
    this.albumName = albumName;
    return this;
  }

   /**
   * Get albumName
   * @return albumName
  **/
  @Schema(description = "")
  public String getAlbumName() {
    return albumName;
  }

  public void setAlbumName(String albumName) {
    this.albumName = albumName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhotoAlbumsIdBody photoAlbumsIdBody = (PhotoAlbumsIdBody) o;
    return Objects.equals(this.photoFileExtension, photoAlbumsIdBody.photoFileExtension) &&
        Objects.equals(this.photoFileContent, photoAlbumsIdBody.photoFileContent) &&
        Objects.equals(this.albumName, photoAlbumsIdBody.albumName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(photoFileExtension, photoFileContent, albumName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhotoAlbumsIdBody {\n");
    
    sb.append("    photoFileExtension: ").append(toIndentedString(photoFileExtension)).append("\n");
    sb.append("    photoFileContent: ").append(toIndentedString(photoFileContent)).append("\n");
    sb.append("    albumName: ").append(toIndentedString(albumName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
