/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TroopPhotoEntity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class TroopPhotoEntity {
  @SerializedName("troop_photo_id")
  private Integer troopPhotoId = null;

  @SerializedName("photo")
  private String photo = null;

  @SerializedName("thumb")
  private String thumb = null;

  public TroopPhotoEntity troopPhotoId(Integer troopPhotoId) {
    this.troopPhotoId = troopPhotoId;
    return this;
  }

   /**
   * ID of the Troop Photo record
   * @return troopPhotoId
  **/
  @Schema(description = "ID of the Troop Photo record")
  public Integer getTroopPhotoId() {
    return troopPhotoId;
  }

  public void setTroopPhotoId(Integer troopPhotoId) {
    this.troopPhotoId = troopPhotoId;
  }

  public TroopPhotoEntity photo(String photo) {
    this.photo = photo;
    return this;
  }

   /**
   * URL of the photo
   * @return photo
  **/
  @Schema(description = "URL of the photo")
  public String getPhoto() {
    return photo;
  }

  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public TroopPhotoEntity thumb(String thumb) {
    this.thumb = thumb;
    return this;
  }

   /**
   * URL of the thumbnail image
   * @return thumb
  **/
  @Schema(description = "URL of the thumbnail image")
  public String getThumb() {
    return thumb;
  }

  public void setThumb(String thumb) {
    this.thumb = thumb;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TroopPhotoEntity troopPhotoEntity = (TroopPhotoEntity) o;
    return Objects.equals(this.troopPhotoId, troopPhotoEntity.troopPhotoId) &&
        Objects.equals(this.photo, troopPhotoEntity.photo) &&
        Objects.equals(this.thumb, troopPhotoEntity.thumb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(troopPhotoId, photo, thumb);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TroopPhotoEntity {\n");
    
    sb.append("    troopPhotoId: ").append(toIndentedString(troopPhotoId)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    thumb: ").append(toIndentedString(thumb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
