/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UsersIdBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class UsersIdBody {
  @SerializedName("user[last_name]")
  private String userLastName = null;

  @SerializedName("user[first_name]")
  private String userFirstName = null;

  @SerializedName("user[email]")
  private String userEmail = null;

  @SerializedName("user[born_on]")
  private String userBornOn = null;

  @SerializedName("user[home_phone]")
  private String userHomePhone = null;

  @SerializedName("user[cell_phone]")
  private String userCellPhone = null;

  @SerializedName("user[profile_photo_file_name]")
  private String userProfilePhotoFileName = null;

  @SerializedName("user[profile_photo_file_content]")
  private String userProfilePhotoFileContent = null;

  public UsersIdBody userLastName(String userLastName) {
    this.userLastName = userLastName;
    return this;
  }

   /**
   * Get userLastName
   * @return userLastName
  **/
  @Schema(description = "")
  public String getUserLastName() {
    return userLastName;
  }

  public void setUserLastName(String userLastName) {
    this.userLastName = userLastName;
  }

  public UsersIdBody userFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
    return this;
  }

   /**
   * Get userFirstName
   * @return userFirstName
  **/
  @Schema(description = "")
  public String getUserFirstName() {
    return userFirstName;
  }

  public void setUserFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
  }

  public UsersIdBody userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @Schema(description = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public UsersIdBody userBornOn(String userBornOn) {
    this.userBornOn = userBornOn;
    return this;
  }

   /**
   * Get userBornOn
   * @return userBornOn
  **/
  @Schema(description = "")
  public String getUserBornOn() {
    return userBornOn;
  }

  public void setUserBornOn(String userBornOn) {
    this.userBornOn = userBornOn;
  }

  public UsersIdBody userHomePhone(String userHomePhone) {
    this.userHomePhone = userHomePhone;
    return this;
  }

   /**
   * Get userHomePhone
   * @return userHomePhone
  **/
  @Schema(description = "")
  public String getUserHomePhone() {
    return userHomePhone;
  }

  public void setUserHomePhone(String userHomePhone) {
    this.userHomePhone = userHomePhone;
  }

  public UsersIdBody userCellPhone(String userCellPhone) {
    this.userCellPhone = userCellPhone;
    return this;
  }

   /**
   * Get userCellPhone
   * @return userCellPhone
  **/
  @Schema(description = "")
  public String getUserCellPhone() {
    return userCellPhone;
  }

  public void setUserCellPhone(String userCellPhone) {
    this.userCellPhone = userCellPhone;
  }

  public UsersIdBody userProfilePhotoFileName(String userProfilePhotoFileName) {
    this.userProfilePhotoFileName = userProfilePhotoFileName;
    return this;
  }

   /**
   * Get userProfilePhotoFileName
   * @return userProfilePhotoFileName
  **/
  @Schema(description = "")
  public String getUserProfilePhotoFileName() {
    return userProfilePhotoFileName;
  }

  public void setUserProfilePhotoFileName(String userProfilePhotoFileName) {
    this.userProfilePhotoFileName = userProfilePhotoFileName;
  }

  public UsersIdBody userProfilePhotoFileContent(String userProfilePhotoFileContent) {
    this.userProfilePhotoFileContent = userProfilePhotoFileContent;
    return this;
  }

   /**
   * Get userProfilePhotoFileContent
   * @return userProfilePhotoFileContent
  **/
  @Schema(description = "")
  public String getUserProfilePhotoFileContent() {
    return userProfilePhotoFileContent;
  }

  public void setUserProfilePhotoFileContent(String userProfilePhotoFileContent) {
    this.userProfilePhotoFileContent = userProfilePhotoFileContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersIdBody usersIdBody = (UsersIdBody) o;
    return Objects.equals(this.userLastName, usersIdBody.userLastName) &&
        Objects.equals(this.userFirstName, usersIdBody.userFirstName) &&
        Objects.equals(this.userEmail, usersIdBody.userEmail) &&
        Objects.equals(this.userBornOn, usersIdBody.userBornOn) &&
        Objects.equals(this.userHomePhone, usersIdBody.userHomePhone) &&
        Objects.equals(this.userCellPhone, usersIdBody.userCellPhone) &&
        Objects.equals(this.userProfilePhotoFileName, usersIdBody.userProfilePhotoFileName) &&
        Objects.equals(this.userProfilePhotoFileContent, usersIdBody.userProfilePhotoFileContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userLastName, userFirstName, userEmail, userBornOn, userHomePhone, userCellPhone, userProfilePhotoFileName, userProfilePhotoFileContent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersIdBody {\n");
    
    sb.append("    userLastName: ").append(toIndentedString(userLastName)).append("\n");
    sb.append("    userFirstName: ").append(toIndentedString(userFirstName)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userBornOn: ").append(toIndentedString(userBornOn)).append("\n");
    sb.append("    userHomePhone: ").append(toIndentedString(userHomePhone)).append("\n");
    sb.append("    userCellPhone: ").append(toIndentedString(userCellPhone)).append("\n");
    sb.append("    userProfilePhotoFileName: ").append(toIndentedString(userProfilePhotoFileName)).append("\n");
    sb.append("    userProfilePhotoFileContent: ").append(toIndentedString(userProfilePhotoFileContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
