/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * V1YouthsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-12T23:02:08.677823-05:00[America/New_York]")
public class V1YouthsBody {
  @SerializedName("youth[last_name]")
  private String youthLastName = null;

  @SerializedName("youth[first_name]")
  private String youthFirstName = null;

  @SerializedName("youth[email]")
  private String youthEmail = null;

  @SerializedName("youth[born_on]")
  private String youthBornOn = null;

  @SerializedName("youth[scout]")
  private String youthScout = null;

  @SerializedName("youth[home_phone]")
  private String youthHomePhone = null;

  @SerializedName("youth[cell_phone]")
  private String youthCellPhone = null;

  @SerializedName("youth[patrol_id]")
  private Integer youthPatrolId = null;

  @SerializedName("youth[household_id]")
  private Integer youthHouseholdId = null;

  @SerializedName("youth[profile_photo]")
  private String youthProfilePhoto = null;

  @SerializedName("youth[leadership_position_id]")
  private Integer youthLeadershipPositionId = null;

  @SerializedName("youth[create_money_account]")
  private Boolean youthCreateMoneyAccount = null;

  @SerializedName("youth[send_invite]")
  private Boolean youthSendInvite = null;

  public V1YouthsBody youthLastName(String youthLastName) {
    this.youthLastName = youthLastName;
    return this;
  }

   /**
   * Get youthLastName
   * @return youthLastName
  **/
  @Schema(required = true, description = "")
  public String getYouthLastName() {
    return youthLastName;
  }

  public void setYouthLastName(String youthLastName) {
    this.youthLastName = youthLastName;
  }

  public V1YouthsBody youthFirstName(String youthFirstName) {
    this.youthFirstName = youthFirstName;
    return this;
  }

   /**
   * Get youthFirstName
   * @return youthFirstName
  **/
  @Schema(required = true, description = "")
  public String getYouthFirstName() {
    return youthFirstName;
  }

  public void setYouthFirstName(String youthFirstName) {
    this.youthFirstName = youthFirstName;
  }

  public V1YouthsBody youthEmail(String youthEmail) {
    this.youthEmail = youthEmail;
    return this;
  }

   /**
   * Get youthEmail
   * @return youthEmail
  **/
  @Schema(description = "")
  public String getYouthEmail() {
    return youthEmail;
  }

  public void setYouthEmail(String youthEmail) {
    this.youthEmail = youthEmail;
  }

  public V1YouthsBody youthBornOn(String youthBornOn) {
    this.youthBornOn = youthBornOn;
    return this;
  }

   /**
   * Get youthBornOn
   * @return youthBornOn
  **/
  @Schema(description = "")
  public String getYouthBornOn() {
    return youthBornOn;
  }

  public void setYouthBornOn(String youthBornOn) {
    this.youthBornOn = youthBornOn;
  }

  public V1YouthsBody youthScout(String youthScout) {
    this.youthScout = youthScout;
    return this;
  }

   /**
   * Get youthScout
   * @return youthScout
  **/
  @Schema(description = "")
  public String getYouthScout() {
    return youthScout;
  }

  public void setYouthScout(String youthScout) {
    this.youthScout = youthScout;
  }

  public V1YouthsBody youthHomePhone(String youthHomePhone) {
    this.youthHomePhone = youthHomePhone;
    return this;
  }

   /**
   * Get youthHomePhone
   * @return youthHomePhone
  **/
  @Schema(description = "")
  public String getYouthHomePhone() {
    return youthHomePhone;
  }

  public void setYouthHomePhone(String youthHomePhone) {
    this.youthHomePhone = youthHomePhone;
  }

  public V1YouthsBody youthCellPhone(String youthCellPhone) {
    this.youthCellPhone = youthCellPhone;
    return this;
  }

   /**
   * Get youthCellPhone
   * @return youthCellPhone
  **/
  @Schema(description = "")
  public String getYouthCellPhone() {
    return youthCellPhone;
  }

  public void setYouthCellPhone(String youthCellPhone) {
    this.youthCellPhone = youthCellPhone;
  }

  public V1YouthsBody youthPatrolId(Integer youthPatrolId) {
    this.youthPatrolId = youthPatrolId;
    return this;
  }

   /**
   * Get youthPatrolId
   * @return youthPatrolId
  **/
  @Schema(description = "")
  public Integer getYouthPatrolId() {
    return youthPatrolId;
  }

  public void setYouthPatrolId(Integer youthPatrolId) {
    this.youthPatrolId = youthPatrolId;
  }

  public V1YouthsBody youthHouseholdId(Integer youthHouseholdId) {
    this.youthHouseholdId = youthHouseholdId;
    return this;
  }

   /**
   * Get youthHouseholdId
   * @return youthHouseholdId
  **/
  @Schema(description = "")
  public Integer getYouthHouseholdId() {
    return youthHouseholdId;
  }

  public void setYouthHouseholdId(Integer youthHouseholdId) {
    this.youthHouseholdId = youthHouseholdId;
  }

  public V1YouthsBody youthProfilePhoto(String youthProfilePhoto) {
    this.youthProfilePhoto = youthProfilePhoto;
    return this;
  }

   /**
   * Get youthProfilePhoto
   * @return youthProfilePhoto
  **/
  @Schema(description = "")
  public String getYouthProfilePhoto() {
    return youthProfilePhoto;
  }

  public void setYouthProfilePhoto(String youthProfilePhoto) {
    this.youthProfilePhoto = youthProfilePhoto;
  }

  public V1YouthsBody youthLeadershipPositionId(Integer youthLeadershipPositionId) {
    this.youthLeadershipPositionId = youthLeadershipPositionId;
    return this;
  }

   /**
   * Get youthLeadershipPositionId
   * @return youthLeadershipPositionId
  **/
  @Schema(description = "")
  public Integer getYouthLeadershipPositionId() {
    return youthLeadershipPositionId;
  }

  public void setYouthLeadershipPositionId(Integer youthLeadershipPositionId) {
    this.youthLeadershipPositionId = youthLeadershipPositionId;
  }

  public V1YouthsBody youthCreateMoneyAccount(Boolean youthCreateMoneyAccount) {
    this.youthCreateMoneyAccount = youthCreateMoneyAccount;
    return this;
  }

   /**
   * Get youthCreateMoneyAccount
   * @return youthCreateMoneyAccount
  **/
  @Schema(description = "")
  public Boolean isYouthCreateMoneyAccount() {
    return youthCreateMoneyAccount;
  }

  public void setYouthCreateMoneyAccount(Boolean youthCreateMoneyAccount) {
    this.youthCreateMoneyAccount = youthCreateMoneyAccount;
  }

  public V1YouthsBody youthSendInvite(Boolean youthSendInvite) {
    this.youthSendInvite = youthSendInvite;
    return this;
  }

   /**
   * Get youthSendInvite
   * @return youthSendInvite
  **/
  @Schema(description = "")
  public Boolean isYouthSendInvite() {
    return youthSendInvite;
  }

  public void setYouthSendInvite(Boolean youthSendInvite) {
    this.youthSendInvite = youthSendInvite;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1YouthsBody v1YouthsBody = (V1YouthsBody) o;
    return Objects.equals(this.youthLastName, v1YouthsBody.youthLastName) &&
        Objects.equals(this.youthFirstName, v1YouthsBody.youthFirstName) &&
        Objects.equals(this.youthEmail, v1YouthsBody.youthEmail) &&
        Objects.equals(this.youthBornOn, v1YouthsBody.youthBornOn) &&
        Objects.equals(this.youthScout, v1YouthsBody.youthScout) &&
        Objects.equals(this.youthHomePhone, v1YouthsBody.youthHomePhone) &&
        Objects.equals(this.youthCellPhone, v1YouthsBody.youthCellPhone) &&
        Objects.equals(this.youthPatrolId, v1YouthsBody.youthPatrolId) &&
        Objects.equals(this.youthHouseholdId, v1YouthsBody.youthHouseholdId) &&
        Objects.equals(this.youthProfilePhoto, v1YouthsBody.youthProfilePhoto) &&
        Objects.equals(this.youthLeadershipPositionId, v1YouthsBody.youthLeadershipPositionId) &&
        Objects.equals(this.youthCreateMoneyAccount, v1YouthsBody.youthCreateMoneyAccount) &&
        Objects.equals(this.youthSendInvite, v1YouthsBody.youthSendInvite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(youthLastName, youthFirstName, youthEmail, youthBornOn, youthScout, youthHomePhone, youthCellPhone, youthPatrolId, youthHouseholdId, youthProfilePhoto, youthLeadershipPositionId, youthCreateMoneyAccount, youthSendInvite);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1YouthsBody {\n");
    
    sb.append("    youthLastName: ").append(toIndentedString(youthLastName)).append("\n");
    sb.append("    youthFirstName: ").append(toIndentedString(youthFirstName)).append("\n");
    sb.append("    youthEmail: ").append(toIndentedString(youthEmail)).append("\n");
    sb.append("    youthBornOn: ").append(toIndentedString(youthBornOn)).append("\n");
    sb.append("    youthScout: ").append(toIndentedString(youthScout)).append("\n");
    sb.append("    youthHomePhone: ").append(toIndentedString(youthHomePhone)).append("\n");
    sb.append("    youthCellPhone: ").append(toIndentedString(youthCellPhone)).append("\n");
    sb.append("    youthPatrolId: ").append(toIndentedString(youthPatrolId)).append("\n");
    sb.append("    youthHouseholdId: ").append(toIndentedString(youthHouseholdId)).append("\n");
    sb.append("    youthProfilePhoto: ").append(toIndentedString(youthProfilePhoto)).append("\n");
    sb.append("    youthLeadershipPositionId: ").append(toIndentedString(youthLeadershipPositionId)).append("\n");
    sb.append("    youthCreateMoneyAccount: ").append(toIndentedString(youthCreateMoneyAccount)).append("\n");
    sb.append("    youthSendInvite: ").append(toIndentedString(youthSendInvite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
