/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AchievementEntity;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AchievementsApi
 */
@Ignore
public class AchievementsApiTest {

    private final AchievementsApi api = new AchievementsApi();

    /**
     * 
     *
     * Returns a list of available achievements for the member
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1AchievementsTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        AchievementEntity response = api.getV1Achievements(xPartnerToken, xUserToken);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns detailed information about an achievement
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1AchievementsIdTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        Integer awardTypeId = null;
        Integer id = null;
        AchievementEntity response = api.getV1AchievementsId(xPartnerToken, xUserToken, awardTypeId, id);

        // TODO: test validations
    }
}
