/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AwardTypeEntity;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AwardTypesApi
 */
@Ignore
public class AwardTypesApiTest {

    private final AwardTypesApi api = new AwardTypesApi();

    /**
     * 
     *
     * Returns a list of available award types for the member. Active achievements are not included.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1AwardTypesTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        AwardTypeEntity response = api.getV1AwardTypes(xPartnerToken, xUserToken);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns active achievements for a given award type.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1AwardTypesIdTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        Integer id = null;
        AwardTypeEntity response = api.getV1AwardTypesId(xPartnerToken, xUserToken, id);

        // TODO: test validations
    }
}
