/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.MailingListEntity;
import io.swagger.client.model.MailingListsIdBody;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MailingListsApi
 */
@Ignore
public class MailingListsApiTest {

    private final MailingListsApi api = new MailingListsApi();

    /**
     * 
     *
     * Returns a list of mailing lists relevant to the user
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1MailingListsTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        List<MailingListEntity> response = api.getV1MailingLists(xPartnerToken, xUserToken);

        // TODO: test validations
    }
    /**
     * 
     *
     * Post a message to a mailing list
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postV1MailingListsIdTest() throws Exception {
        MailingListsIdBody body = null;
        String xPartnerToken = null;
        String xUserToken = null;
        String id = null;
        api.postV1MailingListsId(body, xPartnerToken, xUserToken, id);

        // TODO: test validations
    }
}
