/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OfflineApi
 */
@Ignore
public class OfflineApiTest {

    private final OfflineApi api = new OfflineApi();

    /**
     * 
     *
     * Returns all troop data for cacheing prior to going offline
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1OfflineTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        String troopId = null;
        api.getV1Offline(xPartnerToken, xUserToken, troopId);

        // TODO: test validations
    }
}
