/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UserPrivilegesEntity;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TokensApi
 */
@Ignore
public class TokensApiTest {

    private final TokensApi api = new TokensApi();

    /**
     * 
     *
     * Returns detailed information about a user&#x27;s privileges
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1TokensTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        UserPrivilegesEntity response = api.getV1Tokens(xPartnerToken, xUserToken);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1TokensMyBasicInfoTest() throws Exception {
        api.getV1TokensMyBasicInfo();

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets authentication and privilege information for a user account
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postV1TokensTest() throws Exception {
        String xPartnerToken = null;
        String xUsername = null;
        String xUserPassword = null;
        List<UserPrivilegesEntity> response = api.postV1Tokens(xPartnerToken, xUsername, xUserPassword);

        // TODO: test validations
    }
}
