/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UserAchievementsIdBody;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserAchievementsApi
 */
@Ignore
public class UserAchievementsApiTest {

    private final UserAchievementsApi api = new UserAchievementsApi();

    /**
     * 
     *
     * Returns a list of achievements earned by users based on query parameters.               Query parameters can be combined as desired.               Award type id is required if achievement id is provided
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1UserAchievementsTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        Integer awardTypeId = null;
        Integer userId = null;
        Integer patrolId = null;
        Integer achievementId = null;
        api.getV1UserAchievements(xPartnerToken, xUserToken, awardTypeId, userId, patrolId, achievementId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns achievment details, including requirements, for a given achievement
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1UserAchievementsIdTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        Integer awardTypeId = null;
        Integer id = null;
        api.getV1UserAchievementsId(xPartnerToken, xUserToken, awardTypeId, id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of possible values to be used in querying
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getV1UserAchievementsParametersTest() throws Exception {
        String xPartnerToken = null;
        String xUserToken = null;
        api.getV1UserAchievementsParameters(xPartnerToken, xUserToken);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update achievment details, including requirements, for a given achievement
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postV1UserAchievementsIdTest() throws Exception {
        UserAchievementsIdBody body = null;
        String xPartnerToken = null;
        String xUserToken = null;
        Integer id = null;
        api.postV1UserAchievementsId(body, xPartnerToken, xUserToken, id);

        // TODO: test validations
    }
}
