/*
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.AwardTypeEntity;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AwardTypesApi {
    private ApiClient apiClient;

    public AwardTypesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AwardTypesApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getV1AwardTypes
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getV1AwardTypesCall(String xPartnerToken, String xUserToken, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v1/award_types";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (xPartnerToken != null)
        localVarHeaderParams.put("X-Partner-Token", apiClient.parameterToString(xPartnerToken));
        if (xUserToken != null)
        localVarHeaderParams.put("X-User-Token", apiClient.parameterToString(xUserToken));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getV1AwardTypesValidateBeforeCall(String xPartnerToken, String xUserToken, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'xPartnerToken' is set
        if (xPartnerToken == null) {
            throw new ApiException("Missing the required parameter 'xPartnerToken' when calling getV1AwardTypes(Async)");
        }
        // verify the required parameter 'xUserToken' is set
        if (xUserToken == null) {
            throw new ApiException("Missing the required parameter 'xUserToken' when calling getV1AwardTypes(Async)");
        }
        
        com.squareup.okhttp.Call call = getV1AwardTypesCall(xPartnerToken, xUserToken, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Returns a list of available award types for the member. Active achievements are not included.
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @return AwardTypeEntity
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AwardTypeEntity getV1AwardTypes(String xPartnerToken, String xUserToken) throws ApiException {
        ApiResponse<AwardTypeEntity> resp = getV1AwardTypesWithHttpInfo(xPartnerToken, xUserToken);
        return resp.getData();
    }

    /**
     * 
     * Returns a list of available award types for the member. Active achievements are not included.
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @return ApiResponse&lt;AwardTypeEntity&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AwardTypeEntity> getV1AwardTypesWithHttpInfo(String xPartnerToken, String xUserToken) throws ApiException {
        com.squareup.okhttp.Call call = getV1AwardTypesValidateBeforeCall(xPartnerToken, xUserToken, null, null);
        Type localVarReturnType = new TypeToken<AwardTypeEntity>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Returns a list of available award types for the member. Active achievements are not included.
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getV1AwardTypesAsync(String xPartnerToken, String xUserToken, final ApiCallback<AwardTypeEntity> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getV1AwardTypesValidateBeforeCall(xPartnerToken, xUserToken, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AwardTypeEntity>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getV1AwardTypesId
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @param id  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getV1AwardTypesIdCall(String xPartnerToken, String xUserToken, Integer id, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v1/award_types/{id}"
            .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (xPartnerToken != null)
        localVarHeaderParams.put("X-Partner-Token", apiClient.parameterToString(xPartnerToken));
        if (xUserToken != null)
        localVarHeaderParams.put("X-User-Token", apiClient.parameterToString(xUserToken));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getV1AwardTypesIdValidateBeforeCall(String xPartnerToken, String xUserToken, Integer id, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'xPartnerToken' is set
        if (xPartnerToken == null) {
            throw new ApiException("Missing the required parameter 'xPartnerToken' when calling getV1AwardTypesId(Async)");
        }
        // verify the required parameter 'xUserToken' is set
        if (xUserToken == null) {
            throw new ApiException("Missing the required parameter 'xUserToken' when calling getV1AwardTypesId(Async)");
        }
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getV1AwardTypesId(Async)");
        }
        
        com.squareup.okhttp.Call call = getV1AwardTypesIdCall(xPartnerToken, xUserToken, id, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Returns active achievements for a given award type.
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @param id  (required)
     * @return AwardTypeEntity
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AwardTypeEntity getV1AwardTypesId(String xPartnerToken, String xUserToken, Integer id) throws ApiException {
        ApiResponse<AwardTypeEntity> resp = getV1AwardTypesIdWithHttpInfo(xPartnerToken, xUserToken, id);
        return resp.getData();
    }

    /**
     * 
     * Returns active achievements for a given award type.
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @param id  (required)
     * @return ApiResponse&lt;AwardTypeEntity&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AwardTypeEntity> getV1AwardTypesIdWithHttpInfo(String xPartnerToken, String xUserToken, Integer id) throws ApiException {
        com.squareup.okhttp.Call call = getV1AwardTypesIdValidateBeforeCall(xPartnerToken, xUserToken, id, null, null);
        Type localVarReturnType = new TypeToken<AwardTypeEntity>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Returns active achievements for a given award type.
     * @param xPartnerToken Your secret partner token (required)
     * @param xUserToken The token you received when you authenticated the user (required)
     * @param id  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getV1AwardTypesIdAsync(String xPartnerToken, String xUserToken, Integer id, final ApiCallback<AwardTypeEntity> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getV1AwardTypesIdValidateBeforeCall(xPartnerToken, xUserToken, id, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AwardTypeEntity>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
